---
# vars file for roles/install-docker

docker_required_packages:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg-agent"
  - "software-properties-common"
  - "python3-pip"
  - "python3-setuptools"

docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg

docker_repo_arm64: "deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable"
docker_repo_x86: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

docker_packges:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
